security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
        AppBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    - { name: 'admin@mail.com', password: 'c4ca4238a0b923820dcc509a6f75849b', roles: 'ROLE_ADMIN' }
        user_db:
            entity: { class: AppBundle\Entity\User, property: email }

    #role_hierarchy:
        #ROLE_ADMIN: ROLE_USER

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: authorization
                check_path: authorization
            logout:
                path: logout
                target: /
            provider: chain_provider

    access_control:
        - { path: ^/secret, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    access_denied_url:
        /error403
